export const Smells = {
  abstract_class_no_methods_detector: {
    category: "design",
    color: "#1E1E1E",
    weight: 3,
    code: "ABS",
  },
  coupling_between_objects_detector: {
    category: "design",
    color: "#2E2E2E",
    weight: 3,
    code: "COB",
  },
  cyclomatic_complexity_detector: {
    category: "design",
    color: "#3E3E3E",
    weight: 3,
    code: "CYC",
  },
  excessive_imports_detector: {
    category: "design",
    color: "#4E4E4E",
    weight: 3,
    code: "EXI",
  },
  excessive_parameter_list_detector: {
    category: "design",
    color: "#5E5E5E",
    weight: 3,
    code: "EXP",
  },
  excessive_public_counts_detector: {
    category: "design",
    color: "#6E6E6E",
    weight: 3,
    code: "EPC",
  },
  ncss_detector: {
    category: "design",
    color: "#7E7E7E",
    weight: 3,
    code: "NSD",
  },
  nested_if_detector: {
    category: "design",
    color: "#8E8E8E",
    weight: 3,
    code: "NED",
  },
  null_pointer_exception_detector: {
    category: "design",
    color: "#9E9E9E",
    weight: 3,
    code: "NPD",
  },
  private_constructors_final_detector: {
    category: "design",
    color: "#AE4E4E",
    weight: 3,
    code: "PRV",
  },
  raw_exception_types_detector: {
    category: "design",
    color: "#BE6E6E",
    weight: 3,
    code: "RWD",
  },
  switch_density_detector: {
    category: "design",
    color: "#CE8E8E",
    weight: 3,
    code: "SWD",
  },
  too_many_fields_detector: {
    category: "design",
    color: "#DEAE4E",
    weight: 3,
    code: "TMF",
  },
  too_many_methods_detector: {
    category: "design",
    color: "#EECE6E",
    weight: 3,
    code: "TMM",
  },
  unchecked_exceptions_detector: {
    category: "design",
    color: "#FEDE8E",
    weight: 3,
    code: "UCD",
  },
  useless_overriding_detector: {
    category: "design",
    color: "#0F0F0F",
    weight: 3,
    code: "USD",
  },
  utility_class_detector: {
    category: "design",
    color: "#1F1F1F",
    weight: 3,
    code: "UTD",
  },
};
